
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author trm
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jOptionPane1 = new javax.swing.JOptionPane();
        TextArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        MenuPrincipal = new javax.swing.JMenuBar();
        ArchivoMenu = new javax.swing.JMenu();
        AbrirItem = new javax.swing.JMenuItem();
        GuardarItem = new javax.swing.JMenuItem();
        AyudaMenu = new javax.swing.JMenu();
        InfoMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bloc del codigo");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        TextArea.setViewportView(jTextArea1);

        ArchivoMenu.setText("Archivo");

        AbrirItem.setText("Abrir");
        AbrirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirItemActionPerformed(evt);
            }
        });
        ArchivoMenu.add(AbrirItem);

        GuardarItem.setText("Guardar");
        GuardarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarItemActionPerformed(evt);
            }
        });
        ArchivoMenu.add(GuardarItem);

        MenuPrincipal.add(ArchivoMenu);

        AyudaMenu.setText("Ayuda");

        InfoMenu.setText("Info");
        InfoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoMenuActionPerformed(evt);
            }
        });
        AyudaMenu.add(InfoMenu);

        MenuPrincipal.add(AyudaMenu);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoMenuActionPerformed
        jOptionPane1.showMessageDialog(null, "Desarrollado en Cetys por:\n Tomás Rodríguez-Mata");
    }//GEN-LAST:event_InfoMenuActionPerformed

    private void AbrirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirItemActionPerformed
        abrirFile();
    }//GEN-LAST:event_AbrirItemActionPerformed

    private void GuardarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarItemActionPerformed
        guardarFile();
    }//GEN-LAST:event_GuardarItemActionPerformed

    public void guardarFile(){
        int seleccion = jFileChooser1.showSaveDialog(jTextArea1);
        if (seleccion==0){
            try {
                PrintWriter writer = null;
                File archivo = jFileChooser1.getSelectedFile();
                writer = new PrintWriter(archivo);
                writer.print(jTextArea1.getText());
                writer.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Hubo algun problema en guardar el archivo" + ex.toString()); 
            }
        }
    }
    
    public void abrirFile(){
        int seleccion = jFileChooser1.showOpenDialog(TextArea);
        // Si abren un archivo = 0
        if (seleccion==0){
            try {
                BufferedReader reader = null;
                File archivo = jFileChooser1.getSelectedFile();
                reader = new BufferedReader(new FileReader(archivo));
                // Guarda primera linea del documento
                String linea = reader.readLine();
                while(linea!=null){
                    jTextArea1.append(linea);
                    jTextArea1.append(System.getProperty("line.separator"));
                    linea = reader.readLine();
                }
                reader.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Archivo no encontrado" + ex.toString()); 
            } catch (IOException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Error al acceder al fichero para leerlo" + ex.toString()); 
            }
        }
    }
    
    /**
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirItem;
    private javax.swing.JMenu ArchivoMenu;
    private javax.swing.JMenu AyudaMenu;
    private javax.swing.JMenuItem GuardarItem;
    private javax.swing.JMenuItem InfoMenu;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JScrollPane TextArea;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
